# Railway Configuration - FORCE Java Spring Boot Build
[build]
builder = "HEROKU"
buildpacks = ["https://github.com/heroku/heroku-buildpack-java"]
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/validacao-documentos-1.0.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
JAVA_OPTS = "-Xmx512m"
