# Railway Configuration - FORCE Java Spring Boot Build
[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/validacao-documentos-1.0.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_JAVA_VERSION = "17"
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
RAILWAY_DOCKERFILE_PATH = ""
