# Railway Configuration - Test without MySQL
nixpacks = false

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "test"
