# Railway Configuration - Native Java Build
[build]
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
